# Generated by Django 4.1.6 on 2023-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
