# Generated by Django 4.1.6 on 2023-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
