# Generated by Django 4.1.6 on 2023-02-08 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
