# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gen_default_currency_pb2 as gen__default__currency__pb2


class CurrencyStub(object):
    """Define the Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.generateDefaultCurrency = channel.unary_unary(
                '/Currency/generateDefaultCurrency',
                request_serializer=gen__default__currency__pb2.DefaultCurrencyRequest.SerializeToString,
                response_deserializer=gen__default__currency__pb2.DefaultCurrencyResponse.FromString,
                )


class CurrencyServicer(object):
    """Define the Service
    """

    def generateDefaultCurrency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'generateDefaultCurrency': grpc.unary_unary_rpc_method_handler(
                    servicer.generateDefaultCurrency,
                    request_deserializer=gen__default__currency__pb2.DefaultCurrencyRequest.FromString,
                    response_serializer=gen__default__currency__pb2.DefaultCurrencyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Currency', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Currency(object):
    """Define the Service
    """

    @staticmethod
    def generateDefaultCurrency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/generateDefaultCurrency',
            gen__default__currency__pb2.DefaultCurrencyRequest.SerializeToString,
            gen__default__currency__pb2.DefaultCurrencyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
