# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gen_default_currency.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1agen_default_currency.proto")\n\x16\x44\x65\x66\x61ultCurrencyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03"3\n\x17\x44\x65\x66\x61ultCurrencyResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t2X\n\x08\x43urrency\x12L\n\x17generateDefaultCurrency\x12\x17.DefaultCurrencyRequest\x1a\x18.DefaultCurrencyResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gen_default_currency_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DEFAULTCURRENCYREQUEST._serialized_start = 30
    _DEFAULTCURRENCYREQUEST._serialized_end = 71
    _DEFAULTCURRENCYRESPONSE._serialized_start = 73
    _DEFAULTCURRENCYRESPONSE._serialized_end = 124
    _CURRENCY._serialized_start = 126
    _CURRENCY._serialized_end = 214
# @@protoc_insertion_point(module_scope)
